authors:
  kamilkrzyskow:
    name: HRY
    description: >
      Enthusiast of hacky solutions. Python generalist, without AI or math <span class="twemoji"><img src="https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f605.svg"></span>
    avatar: https://avatars.githubusercontent.com/u/34622465
    slug: hry
    url: https://github.com/Made-by-HRY